# THIS FILE IS AUTOGENERATED BY THE AUTOREGISTRY PLUGIN.
# DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
#
# Class containing preloaded data entries for the 'Events' registry (Core).

class_name Events

const SPAWN_ENTITY: EventEntry = preload("res://data/core/events/spawn_entity.tres")
const PLAYER_MOVED: EventEntry = preload("res://data/core/events/player/moved.tres")

static var ALL: Array[EventEntry] = [SPAWN_ENTITY, PLAYER_MOVED]

static func get_all() -> Array[EventEntry]:
    return ALL
