# THIS FILE IS AUTOGENERATED BY THE AUTOREGISTRY PLUGIN.
# DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
#
# Class containing preloaded data entries for the 'SceneSets' registry (Core).

class_name SceneSets

const TEST: SceneSetEntry = preload("res://data/core/scene_sets/test.tres")

static var ALL: Array[SceneSetEntry] = [TEST]

static func get_all() -> Array[SceneSetEntry]:
    return ALL
