# THIS FILE IS AUTOGENERATED BY THE AUTOREGISTRY PLUGIN.
# DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
#
# Class containing preloaded data entries for the 'ShooterPatterns' registry (Game).

class_name ShooterPatterns

const BASE_ENEMY_PATTERN: ShooterPatternEntry = preload("res://data/game/shooter_patterns/base_enemy_pattern.tres")

static var ALL: Array[ShooterPatternEntry] = [BASE_ENEMY_PATTERN]

static func get_all() -> Array[ShooterPatternEntry]:
    return ALL
